CREATE TABLE links (
  id SERIAL PRIMARY KEY,
  url TEXT NOT NULL,
  code VARCHAR(50) UNIQUE NOT NULL,
  clicks INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_clicked TIMESTAMP
);
